name: Example Workflow

on:
  push:
    branches:
      - Sprint2_Adam

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a simple command
        run: echo "Hello from GitHub Actions!"
m
